// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Constants from "../../utils/Constants.bs.js";
import * as Belt_Float from "rescript/lib/es6/belt_Float.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function handleSubmit(data, setState) {
  var amount = Belt_Option.getExn(Belt_Float.fromString(data.amount));
  if (amount === 0.0) {
    return Constants.zero_amount_warning(undefined);
  } else {
    return Curry._1(setState, (function (prevState) {
                  return {
                          income: amount > 0.0 ? prevState.income + amount : prevState.income,
                          expense: amount < 0.0 ? prevState.expense + amount * -1.0 : prevState.expense,
                          history: (prevState.history.unshift(data), prevState.history)
                        };
                }));
  }
}

export {
  handleSubmit ,
  
}
/* No side effect */
