// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Header from "../Header/Header.bs.js";
import * as Amounts from "../Amounts/Amounts.bs.js";
import * as Balance from "../Balance/Balance.bs.js";
import * as $$History from "../History/History.bs.js";
import * as $$Storage from "../../utils/Storage.bs.js";
import * as Constants from "../../utils/Constants.bs.js";
import * as AddTxnForm from "../AddTxnForm/AddTxnForm.bs.js";

import './App.css'
;

function App(Props) {
  var match = React.useState(function () {
        return {
                income: 0.0,
                expense: 0.0,
                history: []
              };
      });
  var setState = match[1];
  var state = match[0];
  React.useEffect((function () {
          Curry._1(setState, (function (param) {
                  return $$Storage.getFromSessionStorage(Constants.session_storage_key, (function (prim) {
                                return JSON.parse(prim);
                              }));
                }));
          
        }), []);
  React.useEffect((function () {
          $$Storage.setToSessionStorage(Constants.session_storage_key, state);
          
        }), [state]);
  return React.createElement("div", {
              className: "flex-col",
              id: "App"
            }, React.createElement(Header.make, {}), React.createElement(Balance.make, {
                  balance: state.income - state.expense
                }), React.createElement(Amounts.make, {
                  income: state.income,
                  expense: state.expense
                }), React.createElement($$History.make, {
                  history: state.history
                }), React.createElement(AddTxnForm.make, {
                  appSetState: setState
                }));
}

var make = App;

export {
  make ,
  
}
/*  Not a pure module */
