// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Amount from "../Amount/Amount.bs.js";
import * as Header from "../Header/Header.bs.js";
import * as Balance from "../Balance/Balance.bs.js";
import * as $$History from "../History/History.bs.js";
import * as $$Storage from "../../utils/Storage.bs.js";
import * as AppUtils from "./AppUtils.bs.js";
import * as Constants from "../../utils/Constants.bs.js";
import * as AddTransactionForm from "../AddTransactionForm/AddTransactionForm.bs.js";

import './App.css'
;

function App(Props) {
  var match = React.useState(function () {
        return $$Storage.getFromSessionStorage(Constants.session_storage_key, (function (prim) {
                      return JSON.parse(prim);
                    }));
      });
  var transactions = match[0];
  React.useEffect((function () {
          $$Storage.setToSessionStorage(Constants.session_storage_key, transactions);
          
        }), [transactions]);
  return React.createElement("div", {
              className: "app"
            }, React.createElement("div", {
                  className: "flex-col app-container"
                }, React.createElement(Header.make, {}), React.createElement(Balance.make, {
                      balance: AppUtils.getTotalIncome(transactions) - AppUtils.getTotalExpense(transactions)
                    }), React.createElement(Amount.make, {
                      income: AppUtils.getTotalIncome(transactions),
                      expense: AppUtils.getTotalExpense(transactions)
                    }), React.createElement($$History.make, {
                      history: transactions
                    }), React.createElement(AddTransactionForm.make, {
                      update_state: match[1]
                    })));
}

var make = App;

export {
  make ,
  
}
/*  Not a pure module */
