// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Constants from "../../utils/Constants.bs.js";

function Header(Props) {
  return React.createElement("h1", {
              className: "text-align-center"
            }, Constants.header);
}

var make = Header;

export {
  make ,
  
}
/* react Not a pure module */
