// Generated by ReScript, PLEASE EDIT WITH CARE


function zero_amount_warning(param) {
  ((alert('Zero amount not allowed!!!')));
  
}

var amount_label = {
  label: "Amount ",
  "sub-label": "( Negative - Expense , Positive - Income )"
};

var session_storage_key = "Expense Tracker";

var header = "EXPENSE TRACKER";

var remark_label = "Remark";

var remark_placeholder = "Enter remark";

var amount_placeholder = "Enter amount";

var submit_button_label = "Add Transaction";

export {
  session_storage_key ,
  zero_amount_warning ,
  header ,
  remark_label ,
  remark_placeholder ,
  amount_label ,
  amount_placeholder ,
  submit_button_label ,
  
}
/* No side effect */
