// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function setToSessionStorage(key, value) {
  sessionStorage.setItem(key, Belt_Option.getExn(JSON.stringify(value)));
  
}

function getFromSessionStorage(key, parser) {
  var json = sessionStorage.getItem(key);
  if (json !== null) {
    return Curry._1(parser, json);
  } else {
    return [];
  }
}

export {
  setToSessionStorage ,
  getFromSessionStorage ,
  
}
/* No side effect */
