// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as HistoryUtils from "./HistoryUtils.bs.js";

import './History.css'
;

function $$History(Props) {
  var history = Props.history;
  return React.createElement("div", {
              className: "flex-col gap-2",
              id: "History"
            }, React.createElement("h3", {
                  className: "border-btm bold"
                }, "HISTORY"), React.createElement("div", {
                  className: "flex-col gap-1",
                  id: "history-list"
                }, Belt_Array.mapWithIndex(history, (function (index, record) {
                        return HistoryUtils.html_generator(record, index);
                      }))));
}

var make = $$History;

export {
  make ,
  
}
/*  Not a pure module */
