// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Float from "rescript/lib/es6/belt_Float.js";

function html_generator(record, index) {
  var amt = Belt_Float.fromString(record.amount);
  var className = amt !== undefined ? (
      amt > 0.0 ? "history-record-income" : "history-record-expense"
    ) : "";
  var amount = Belt_Float.fromString(record.amount);
  return React.createElement("div", {
              key: String(index),
              className: className + " flex-row"
            }, React.createElement("p", undefined, record.remark), React.createElement("p", {
                  className: ""
                }, React.createElement("em", undefined, "$ "), amount !== undefined ? (
                    amount > 0.0 ? String(amount) : String(amount * -1.0)
                  ) : ""));
}

export {
  html_generator ,
  
}
/* react Not a pure module */
