// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Float from "rescript/lib/es6/belt_Float.js";

function content_generator(record, index, getAccordionItemClass, accordionOnClick) {
  var amt = Belt_Float.fromString(record.amount);
  var className = amt !== undefined ? (
      amt > 0.0 ? "income" : "expense"
    ) : "";
  var amount = Belt_Float.fromString(record.amount);
  return React.createElement("div", {
              key: String(index),
              className: className + " history-record flex-row " + Curry._1(getAccordionItemClass, index),
              onClick: (function (param) {
                  return Curry._1(accordionOnClick, index);
                })
            }, React.createElement("p", undefined, record.remark), React.createElement("p", {
                  className: ""
                }, React.createElement("em", undefined, "$ "), amount !== undefined ? (
                    amount > 0.0 ? String(amount) : String(amount * -1.0)
                  ) : ""));
}

export {
  content_generator ,
  
}
/* react Not a pure module */
