// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

import './Amounts.css'
;

function Amounts(Props) {
  var income = Props.income;
  var expense = Props.expense;
  return React.createElement("div", {
              className: "flex-row",
              id: "Amounts"
            }, React.createElement("div", {
                  className: "flex-1 flex-col align-center gap-1",
                  id: "income-card"
                }, React.createElement("h3", {
                      className: "bold"
                    }, "INCOME"), React.createElement("p", {
                      className: "amount"
                    }, React.createElement("em", undefined, "$ "), String(income))), React.createElement("div", {
                  id: "amounts-border"
                }), React.createElement("div", {
                  className: "flex-1 flex-col align-center gap-1",
                  id: "expense-card"
                }, React.createElement("h3", {
                      className: "bold"
                    }, "EXPENSE"), React.createElement("p", {
                      className: "amount"
                    }, React.createElement("em", undefined, "$ "), String(expense))));
}

var make = Amounts;

export {
  make ,
  
}
/*  Not a pure module */
